language: node_js
node_js:
  - "6"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo apt-get update

script:
  - npm install
  - bower install
  - npm run test-single