language: node_js
node_js:
  - "6"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - npm install
  - bower install
script: node_modules/karma/bin/karma start test/karma.conf.js --single-run